--https://www.postgresql.org/docs/current/sql-droptable.html
DROP TABLE IF EXISTS ERS_USER_ROLES, ERS_USERS, ERS_REIMBURSEMENT_STATUSES, ERS_REIMBURSEMENT_TYPES, ERS_REIMBURSEMENTS;
--DROP TABLE IF EXISTS ERS_USER_ROLES;
CREATE TABLE ERS_USER_ROLES (
	ROLE_ID VARCHAR(255) PRIMARY KEY,
	ROLE VARCHAR(255) UNIQUE
);
--https://www.postgresql.org/docs/8.3/tutorial-fk.html
--DROP TABLE IF EXISTS ERS_USERS;
CREATE TABLE ERS_USERS (
	USER_ID VARCHAR(255) PRIMARY KEY,
	USERNAME VARCHAR(255) UNIQUE NOT NULL,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	GIVEN_NAME VARCHAR(255) NOT NULL,
	SURNAME VARCHAR(255) NOT NULL,
	IS_ACTIVE BOOLEAN,
	ROLE_ID VARCHAR(255) REFERENCES ERS_USER_ROLES(ROLE_ID)
);
--DROP TABLE IF EXISTS ERS_REIMBURSEMENT_STATUSES;
CREATE TABLE ERS_REIMBURSEMENT_STATUSES (
	STATUS_ID VARCHAR(255) PRIMARY KEY,
	STATUS VARCHAR(255) UNIQUE
);
--DROP TABLE IF EXISTS ERS_REIMBURSEMENT_TYPES;
CREATE TABLE ERS_REIMBURSEMENT_TYPES (
	TYPE_ID VARCHAR(255) PRIMARY KEY,
	TYPE VARCHAR(255) UNIQUE
);
--https://www.postgresql.org/docs/9.6/datatype-numeric.html
--https://www.postgresql.org/docs/9.1/datatype-binary.html
--DROP TABLE IF EXISTS ERS_REIMBURSEMENTS;
CREATE TABLE ERS_REIMBURSEMENTS (
	REIMB_ID VARCHAR(255) PRIMARY KEY,
	AMOUNT NUMERIC(6,2) NOT NULL,
	SUBMITTED TIMESTAMP NOT NULL,
	RESOLVED TIMESTAMP,
	DESCRIPTION VARCHAR(255) NOT NULL,
	RECEIPT BYTEA,
	PAYMENT_ID VARCHAR(255),
	AUTHOR_ID VARCHAR(255) NOT NULL REFERENCES ERS_USERS(USER_ID),
	RESOLVER_ID VARCHAR(255) REFERENCES ERS_USERS,
	STATUS_ID VARCHAR(255) NOT NULL REFERENCES ERS_REIMBURSEMENT_STATUSES(STATUS_ID),
	TYPE_ID VARCHAR(255) NOT NULL REFERENCES ERS_REIMBURSEMENT_TYPES(TYPE_ID)
);
--FK RESOLVER_ID?
